# Generated by Django 6.1.1 on 2026-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentledgerentry',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentledgerentry',
            name='previous_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set only if this entry was later edited — what it was before.', max_digits=14, null=True),
        ),
    ]
