# Generated by Django 6.1.1 on 2026-09-15 07:22

import django.core.validators
import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('scope', models.CharField(choices=[('customer', 'Customer KYC Document'), ('loan', 'Loan Document')], default='customer', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['scope', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, help_text='ID / document number. Required if no file is uploaded.', max_length=100)),
                ('file', models.FileField(blank=True, help_text='PDF, JPG, JPEG or PNG. Optional if a document number is provided instead.', null=True, upload_to=documents.models.customer_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), documents.models.validate_document_file_size])),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('verified_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('document_type', models.ForeignKey(limit_choices_to={'is_active': True, 'scope': 'customer'}, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
            ],
            options={
                'ordering': ['document_type__display_order', '-uploaded_date'],
            },
        ),
    ]
