# Generated by Django 6.1.1 on 2026-09-15 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('alternate_mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('father_husband_name', models.CharField(max_length=150)),
                ('permanent_door_no', models.CharField(max_length=50)),
                ('permanent_street', models.CharField(max_length=150)),
                ('permanent_area', models.CharField(max_length=150)),
                ('permanent_village_town', models.CharField(max_length=150)),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_district', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(max_length=100)),
                ('permanent_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode.', regex='^\\d{6}$')])),
                ('same_as_permanent_address', models.BooleanField(default=True)),
                ('current_door_no', models.CharField(blank=True, max_length=50)),
                ('current_street', models.CharField(blank=True, max_length=150)),
                ('current_area', models.CharField(blank=True, max_length=150)),
                ('current_village_town', models.CharField(blank=True, max_length=150)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('current_district', models.CharField(blank=True, max_length=100)),
                ('current_state', models.CharField(blank=True, max_length=100)),
                ('current_pincode', models.CharField(blank=True, max_length=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code (e.g. HDFC0001234).', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=150)),
                ('reference_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('reference_address', models.TextField()),
                ('relationship', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='customers.customer')),
            ],
        ),
    ]
