# Generated by Django 6.1.1 on 2026-10-09 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='permanent_area',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='permanent_door_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='permanent_street',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
