# Generated by Django 6.1.1 on 2026-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_permanent_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='permanent_village_town',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
