# Generated by Django 6.1.1 on 2026-09-16 09:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='interest_component',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='installment',
            name='principal_component',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='interesttype',
            name='calculation_method',
            field=models.CharField(choices=[('flat', 'Flat Interest'), ('reducing', 'Reducing Balance')], default='flat', max_length=20),
        ),
    ]
