# Generated by Django 6.1.1 on 2026-09-30 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='penalty_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty charged for each day an installment remains overdue.', max_digits=10),
        ),
    ]
