# Generated by Django 6.1.1 on 2026-10-08 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_strict_voucher_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
