# Generated by Django 6.1.1 on 2026-09-19 12:09

import django.core.validators
import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_customerdocument_archived_at_and_more'),
        ('loans', '0002_installment_interest_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, help_text="Reference number, if there's no file to attach.", max_length=100)),
                ('file', models.FileField(blank=True, help_text='PDF, JPG, JPEG or PNG. Optional if a reference number is provided instead.', null=True, upload_to=documents.models.loan_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), documents.models.validate_document_file_size])),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('verified_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('document_type', models.ForeignKey(limit_choices_to={'is_active': True, 'scope': 'loan'}, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loan')),
            ],
            options={
                'ordering': ['document_type__display_order', '-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, help_text='Optional — link an uploaded scan of the notice letter itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='documents.loandocument')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='loans.loan')),
                ('notice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.noticetype')),
            ],
            options={
                'ordering': ['-notice_date'],
            },
        ),
    ]
