# Generated by Django 6.1.1 on 2026-09-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_noticetype_loandocument_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('agreement', 'Loan Agreement'), ('notice', 'Overdue Notice'), ('closing', 'Loan Closing Document')], max_length=20, unique=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
